input tests

diff --git a/tester b/tester
--- a/tester
+++ b/tester
@@ -1,6 +1,6 @@
 #!/bin/sh
 # this is the path to the mandatory philo executable
-P="../philo/philo"
+P="../philo"
 # this is the path to the bonus philo executable
 PB="../philo_bonus/philo_bonus"
 
@@ -48,6 +48,8 @@ ft_print_status()
 {
 	if [ $2 -eq 1 ]; then
 		printf "$PURPLE TEST $1:$GREEN Success!$RESET\n"
+	elif [ $(echo "abcdefgh" | tr -cd $2 | wc -c) -gt 0 ]; then
+		printf "$PURPLE TEST $1:$RED Fail!$RESET\n"
 	elif [ $2 -eq 0 ] && [ $1 -lt 7 ]; then
 		printf "$PURPLE TEST $1:$RED Fail!$RESET\n"
 	elif [ $2 -eq 0 ] && [ $1 -gt 6 ]; then
@@ -61,11 +63,184 @@ ft_print_status()
 ft_test_a()
 {
 	file="./loga"
-	status=0
-	$1 >$file &
+	status=1
+	$($BUFF $1 >$file &)
 	sleep 1
-	pid=$(pgrep $1)
+	if ! [ "$(pgrep philo)" = "" ]; then
+		status=0
+		kill -kill $(pgrep philo) 2>/dev/null
+	elif [ $(cat $file | grep "fault" | wc -l | awk '{print $1}') -gt 0 ]; then
+		status=0
+	elif [ $(cat $file | grep "Error" | wc -l | awk '{print $1}') -gt 0 ]; then
+		status=1
+	elif [ $(cat $file | wc -l | awk '{print $1}') -gt 2 ]; then
+		status=0
+	fi
+	if [ $status -eq 1 ]; then
+		rm $file 2>/dev/null
+	fi
+	ft_print_status "a" $status
+}
 
+# ./philo 4 410 200
+ft_test_b()
+{
+	file="./logb"
+	status=1
+	$($BUFF $1 4 410 200 >$file &)
+	sleep 1
+	if ! [ "$(pgrep philo)" = "" ]; then
+		status=0
+		kill -kill $(pgrep philo) 2>/dev/null
+	elif [ $(cat $file | grep "fault" | wc -l | awk '{print $1}') -gt 0 ]; then
+		status=0
+	elif [ $(cat $file | grep "Error" | wc -l | awk '{print $1}') -gt 0 ]; then
+		status=1
+	elif [ $(cat $file | wc -l | awk '{print $1}') -gt 2 ]; then
+		status=0
+	fi
+	if [ $status -eq 1 ]; then
+		rm $file 2>/dev/null
+	fi
+	ft_print_status "b" $status
+}
+
+# ./philo 4 410 200 200 3 1
+ft_test_c()
+{
+	file="./logc"
+	status=1
+	$($BUFF $1 4 410 200 200 3 1 >$file &)
+	sleep 1
+	if ! [ "$(pgrep philo)" = "" ]; then
+		status=0
+		kill -kill $(pgrep philo) 2>/dev/null
+	elif [ $(cat $file | grep "fault" | wc -l | awk '{print $1}') -gt 0 ]; then
+		status=0
+	elif [ $(cat $file | grep "Error" | wc -l | awk '{print $1}') -gt 0 ]; then
+		status=1
+	elif [ $(cat $file | wc -l | awk '{print $1}') -gt 2 ]; then
+		status=0
+	fi
+	if [ $status -eq 1 ]; then
+		rm $file 2>/dev/null
+	fi
+	ft_print_status "c" $status
+}
+
+# ./philo a 410 200 200
+ft_test_d()
+{
+	file="./logd"
+	status=1
+	$($BUFF $1 a 410 200 200 >$file &)
+	sleep 1
+	if ! [ "$(pgrep philo)" = "" ]; then
+		status=0
+		kill -kill $(pgrep philo) 2>/dev/null
+	elif [ $(cat $file | grep "fault" | wc -l | awk '{print $1}') -gt 0 ]; then
+		status=0
+	elif [ $(cat $file | grep "Error" | wc -l | awk '{print $1}') -gt 0 ]; then
+		status=1
+	elif [ $(cat $file | wc -l | awk '{print $1}') -gt 2 ]; then
+		status=0
+	fi
+	if [ $status -eq 1 ]; then
+		rm $file 2>/dev/null
+	fi
+	ft_print_status "d" $status
+}
+
+# ./philo 4 410 200 200 a
+ft_test_e()
+{
+	file="./loge"
+	status=1
+	$($BUFF $1 4 410 200 200 a >$file &)
+	sleep 1
+	if ! [ "$(pgrep philo)" = "" ]; then
+		status=0
+		kill -kill $(pgrep philo) 2>/dev/null
+	elif [ $(cat $file | grep "fault" | wc -l | awk '{print $1}') -gt 0 ]; then
+		status=0
+	elif [ $(cat $file | grep "Error" | wc -l | awk '{print $1}') -gt 0 ]; then
+		status=1
+	elif [ $(cat $file | wc -l | awk '{print $1}') -gt 2 ]; then
+		status=0
+	fi
+	if [ $status -eq 1 ]; then
+		rm $file 2>/dev/null
+	fi
+	ft_print_status "e" $status
+}
+
+# ./philo -4 410 200 200
+ft_test_f()
+{
+	file="./logf"
+	status=1
+	$($BUFF $1 -4 410 200 200 >$file &)
+	sleep 1
+	if ! [ "$(pgrep philo)" = "" ]; then
+		status=0
+		kill -kill $(pgrep philo) 2>/dev/null
+	elif [ $(cat $file | grep "fault" | wc -l | awk '{print $1}') -gt 0 ]; then
+		status=0
+	elif [ $(cat $file | grep "Error" | wc -l | awk '{print $1}') -gt 0 ]; then
+		status=1
+	elif [ $(cat $file | wc -l | awk '{print $1}') -gt 2 ]; then
+		status=0
+	fi
+	if [ $status -eq 1 ]; then
+		rm $file 2>/dev/null
+	fi
+	ft_print_status "f" $status
+}
+
+# ./philo 4 410 -200 200
+ft_test_g()
+{
+	file="./logg"
+	status=1
+	$($BUFF $1 4 410 -200 200 >$file &)
+	sleep 1
+	if ! [ "$(pgrep philo)" = "" ]; then
+		status=0
+		kill -kill $(pgrep philo) 2>/dev/null
+	elif [ $(cat $file | grep "fault" | wc -l | awk '{print $1}') -gt 0 ]; then
+		status=0
+	elif [ $(cat $file | grep "Error" | wc -l | awk '{print $1}') -gt 0 ]; then
+		status=1
+	elif [ $(cat $file | wc -l | awk '{print $1}') -gt 2 ]; then
+		status=0
+	fi
+	if [ $status -eq 1 ]; then
+		rm $file 2>/dev/null
+	fi
+	ft_print_status "g" $status
+}
+
+# ./philo 4 410 200 200 -3
+ft_test_h()
+{
+	file="./logh"
+	status=1
+	$($BUFF $1 4 410 200 200 -3 >$file &)
+	sleep 1
+	if ! [ "$(pgrep philo)" = "" ]; then
+		status=0
+		kill -kill $(pgrep philo) 2>/dev/null
+	elif [ $(cat $file | grep "fault" | wc -l | awk '{print $1}') -gt 0 ]; then
+		status=0
+	elif [ $(cat $file | grep "Error" | wc -l | awk '{print $1}') -gt 0 ]; then
+		status=1
+	elif [ $(cat $file | wc -l | awk '{print $1}') -gt 2 ]; then
+		status=0
+	fi
+	if [ $status -eq 1 ]; then
+		rm $file 2>/dev/null
+	fi
+	ft_print_status "h" $status
 }
 
 # ./philo 4 410 200 200 3
@@ -116,24 +291,23 @@ ft_test_three()
 {
 	file="./log3"
 	status=1
-	i=0
+	i=120
 	$($BUFF $1 5 610 200 200 >$file &)
-	while [ $i -lt 120 ]; do
-		printf "\033[1K\r$CYAN Executing your program for$PURPLE %d$CYAN seconds, please wait...$RESET" $((120 - i))
+	while [ $i -gt 0 ]; do
+		printf "\033[1K\r$CYAN Executing your program for$PURPLE $i$CYAN seconds, please wait...$RESET"
 		sleep 1
-		i=$((i + 1))
-		if [ "$(pgrep $1)" = "" ]; then
+		i=$((i - 1))
+		if [ "$(pgrep philo)" = "" ]; then
 			status=0
 			break
 		fi
 	done
 	printf "\033[1K\r"
-	kill -kill $(pgrep $1) 2>/dev/null
-	# printf "time: $(cat $file | tail -1 | awk '{print $1}')"
+	kill -kill $(pgrep philo) 2>/dev/null
 	if ! [ "$(grep 'died' $file)" = "" ] || [ "$(cat $file | tail -1)" = "" ]; then
 		status=0
 	elif [ $(cat $file | tail -1 | awk '{print $1}') -lt 100000 ]; then
-		status = 0;
+		status=0;
 	fi
 	if [ $status -eq 1 ]; then
 		rm $file 2>/dev/null
@@ -219,13 +393,13 @@ ft_test_seven()
 		printf "\033[1K\r$CYAN Executing your program for$PURPLE %d$CYAN seconds, please wait...$RESET" $((120 - i))
 		sleep 1
 		i=$((i + 1))
-		if [ "$(pgrep $1)" = "" ]; then
+		if [ "$(pgrep philo)" = "" ]; then
 			status=0
 			break
 		fi
 	done
 	printf "\033[1K\r"
-	kill -kill $(pgrep $1) 2>/dev/null
+	kill -kill $(pgrep philo) 2>/dev/null
 	if ! [ "$(grep 'died' $file)" = "" ] || [ $(cat $file | tail -1 | awk '{print $1}') -lt 100000 ]; then
 		status=0
 	fi
@@ -240,20 +414,20 @@ ft_test_eight()
 {
 	file="./log8"
 	status=1
-	i=0
+	i=60
 	$($BUFF $1 50 410 200 200 1>$file &)
-	while [ $i -lt 120 ]; do
-		printf "\033[1K\r$CYAN Executing your program for$PURPLE %d$CYAN seconds, please wait...$RESET" $((120 - i))
+	while [ $i -gt 0 ]; do
+		printf "\033[1K\r$CYAN Executing your program for$PURPLE $i$CYAN seconds, please wait...$RESET"
 		sleep 1
-		i=$((i + 1))
-		if [ "$(pgrep $1)" = "" ]; then
+		i=$((i - 1))
+		if [ "$(pgrep philo)" = "" ]; then
 			status=0
 			break
 		fi
 	done
 	printf "\033[1K\r"
-	kill -kill $(pgrep $1) 2>/dev/null
-	if ! [ "$(grep 'died' $file)" = "" ] || [ $(cat $file | tail -1 | awk '{print $1}') -lt 100000 ]; then
+	kill -kill $(pgrep philo) 2>/dev/null
+	if ! [ "$(grep 'died' $file)" = "" ] || [ $(cat $file | tail -1 | awk '{print $1}') -lt 50000 ]; then
 		status=0
 	fi
 	if [ $status -eq 1 ]; then
@@ -267,20 +441,20 @@ ft_test_nine()
 {
 	file="./log9"
 	status=1
-	i=0
+	i=60
 	$($BUFF $1 100 410 200 200 1>$file &)
-	while [ $i -lt 120 ]; do
-		printf "\033[1K\r$CYAN Executing your program for$PURPLE %d$CYAN seconds, please wait...$RESET" $((120 - i))
+	while [ $i -gt 0 ]; do
+		printf "\033[1K\r$CYAN Executing your program for$PURPLE $i$CYAN seconds, please wait...$RESET"
 		sleep 1
-		i=$((i + 1))
-		if [ "$(pgrep $1)" = "" ]; then
+		i=$((i - 1))
+		if [ "$(pgrep philo)" = "" ]; then
 			status=0
 			break
 		fi
 	done
 	printf "\033[1K\r"
-	kill -kill $(pgrep $1) 2>/dev/null
-	if ! [ "$(grep 'died' $file)" = "" ] || [ $(cat $file | tail -1 | awk '{print $1}') -lt 100000 ]; then
+	kill -kill $(pgrep philo) 2>/dev/null
+	if ! [ "$(grep 'died' $file)" = "" ] || [ $(cat $file | tail -1 | awk '{print $1}') -lt 50000 ]; then
 		status=0
 	fi
 	if [ $status -eq 1 ]; then
@@ -292,6 +466,14 @@ ft_test_nine()
 ft_do_specific()
 {
 	case $1 in
+		a) ft_test_a $2 ;;
+		b) ft_test_b $2 ;;
+		c) ft_test_c $2 ;;
+		d) ft_test_d $2 ;;
+		e) ft_test_e $2 ;;
+		f) ft_test_f $2 ;;
+		g) ft_test_g $2 ;;
+		h) ft_test_h $2 ;;
 		1) ft_test_one $2 ;;
 		2) ft_test_two $2 ;;
 		3) ft_test_three $2 ;;
@@ -310,6 +492,21 @@ ft_do_specific()
 
 ft_all()
 {
+	printf "To execute all the$YELLOW tests$RESET you'll need to wait at least$GREEN 6$RESET minutes\n"
+	printf "While executing the$YELLOW tests$RESET don't launch other programs$CYAN otherwise$RESET\n"
+	printf "you'll get$RED false$RESET results, so please be patient and$GREEN relax$RESET.\n"
+	printf "If you need to lauch a specific$YELLOW test$RESET you can add its number\n"
+	printf "after the option m, just like this:\n"
+	printf "	$PURPLE./tester$RESET$BLUE m$RESET$GREEN 4$RESET\n"
+	printf "	$PURPLE./tester$RESET$BLUE m$RESET$GREEN f\n"
+	printf "$CYAN Testing some invalid input...$RESET\n"
+	ft_test_a $1
+	ft_test_b $1
+	ft_test_c $1
+	ft_test_d $1
+	ft_test_f $1
+	ft_test_g $1
+	ft_test_h $1
 	if [ "$1" = "$P" ]; then
 		printf "$CYAN Testing mandatory part...$RESET\n"
 	else
@@ -327,14 +524,16 @@ ft_all()
 	ft_test_nine $1
 }
 
-BUFF="stdbuf -oL -eL"
-$BUFF echo ciao > /dev/null 2>&1
-if ! [ $? -eq 0 ] && ! [ "$(uname)" = "Linux" ]; then
+
+if ! [ "$(which stdbuf)" = "" ]; then
+	BUFF="stdbuf -oL -eL"
+elif ! [ "$(which stdbuf)" = "" ] && ! [ "$(uname)" = "Linux" ]; then
 	BUFF=""
 else
 	printf "An error occurred\nTry to install the 'stdbuf' function\n"
 	exit 1
 fi
+
 # check shell that executed the script
 shell_name=$(ps -p $$ -o command | tail -1 | awk '{print $1}')
 slashes=$(($(echo $shell_name | tr -cd / | wc -c | awk '{print $1}') + 1))
